# ruff: noqa: E501  (long comments)
"""Every route's tenancy class (10 section 1.3 item 6). A new route fails tests/tenancy until it is added here.

Classes:
- tenant: acts on a trip or its children. Another user gets 404, a viewer cannot write, no token gets 401.
- user_scoped: acts on the caller's own account. Another user only ever sees their own data.
- public: needs no token (health, waitlist, docs, local dev routes).
- token_feed: authorized by a secret in the URL (calendar feeds, share links). Tested by scenario 18.
- webhook: authorized by a shared secret or signature. Tested by the contract suite.
- admin: tested by the admin suite.

Key: "METHOD /path" exactly as FastAPI registers it. Later prompts add one line per route.
"""

CLASSES = ("tenant", "user_scoped", "public", "token_feed", "webhook", "admin")

POLICY: dict[str, str] = {
    "GET /health/live": "public",
    "GET /health/ready": "public",
    "GET /health/queue": "public",
    "POST /v1/waitlist": "public",
    "GET /v1/unsubscribe": "token_feed",
    "POST /v1/unsubscribe": "token_feed",
    "POST /v1/me/bootstrap": "user_scoped",
    "POST /v1/me/legacy-claim": "user_scoped",
    "GET /v1/me": "user_scoped",
    "GET /v1/me/entitlements": "user_scoped",
    "GET /v1/me/consents": "user_scoped",
    "PUT /v1/me/consents/{kind}": "user_scoped",
    "POST /v1/reports": "user_scoped",
    "GET /v1/geo/destinations": "user_scoped",
    "GET /v1/places/search": "user_scoped",
    "GET /v1/places/{place_id}": "user_scoped",
    "GET /v1/trips/{trip_id}/saved-places": "tenant",
    "POST /v1/trips/{trip_id}/saved-places": "tenant",
    "DELETE /v1/trips/{trip_id}/saved-places/{saved_id}": "tenant",
    "GET /v1/trips": "user_scoped",
    "POST /v1/trips": "user_scoped",
    "GET /v1/trips/{trip_id}": "tenant",
    "PATCH /v1/trips/{trip_id}": "tenant",
    "DELETE /v1/trips/{trip_id}": "tenant",
    "POST /v1/trips/{trip_id}/restore": "tenant",
    "POST /v1/trips/{trip_id}/duplicate": "tenant",
    "GET /v1/trips/{trip_id}/destinations": "tenant",
    "POST /v1/trips/{trip_id}/destinations": "tenant",
    "PUT /v1/trips/{trip_id}/destinations/order": "tenant",
    "PATCH /v1/trips/{trip_id}/destinations/{destination_id}": "tenant",
    "DELETE /v1/trips/{trip_id}/destinations/{destination_id}": "tenant",
    "GET /v1/trips/{trip_id}/routes": "tenant",
    "POST /v1/trips/{trip_id}/routes": "tenant",
    "PUT /v1/trips/{trip_id}/routes/{route_id}": "tenant",
    "DELETE /v1/trips/{trip_id}/routes/{route_id}": "tenant",
    "GET /v1/trips/{trip_id}/routes/{route_id}/fares": "tenant",
    "POST /v1/trips/{trip_id}/flights/refresh": "tenant",
    "GET /v1/trips/{trip_id}/flights/best": "tenant",
    "GET /v1/trips/{trip_id}/flights/summary": "tenant",
    "GET /v1/trips/{trip_id}/routes/{route_id}/price-history": "tenant",
    "GET /v1/trips/{trip_id}/routes/{route_id}/date-grid": "tenant",
    "PATCH /v1/trips/{trip_id}/fares/{fare_id}": "tenant",
    "PUT /v1/trips/{trip_id}/routes/{route_id}/choice": "tenant",
    "DELETE /v1/trips/{trip_id}/routes/{route_id}/choice": "tenant",
    "POST /v1/trips/{trip_id}/routes/{route_id}/choice/booked": "tenant",
    "GET /v1/trips/{trip_id}/price-alerts": "tenant",
    "POST /v1/routes/{route_id}/price-alerts": "tenant",
    "PATCH /v1/price-alerts/{alert_id}": "tenant",
    "DELETE /v1/price-alerts/{alert_id}": "tenant",
    "GET /v1/trips/{trip_id}/items": "tenant",
    "POST /v1/trips/{trip_id}/items": "tenant",
    "POST /v1/trips/{trip_id}/items/bulk": "tenant",
    "GET /v1/items/{item_id}": "tenant",
    "PATCH /v1/items/{item_id}": "tenant",
    "DELETE /v1/items/{item_id}": "tenant",
    "POST /v1/items/{item_id}/move": "tenant",
    "GET /v1/trips/{trip_id}/days": "tenant",
    "PUT /v1/trips/{trip_id}/days/{day}": "tenant",
    "POST /v1/trips/{trip_id}/days/{day}/reorder": "tenant",
    "GET /v1/trips/{trip_id}/itinerary.ics": "tenant",
    "GET /v1/trips/{trip_id}/lodging": "tenant",
    "POST /v1/trips/{trip_id}/lodging": "tenant",
    "GET /v1/trips/{trip_id}/lodging/compare": "tenant",
    "GET /v1/lodging/{option_id}": "tenant",
    "PATCH /v1/lodging/{option_id}": "tenant",
    "DELETE /v1/lodging/{option_id}": "tenant",
    "PUT /v1/lodging/{option_id}/votes/me": "tenant",
    "GET /v1/trips/{trip_id}/notes": "tenant",
    "POST /v1/trips/{trip_id}/notes": "tenant",
    "PATCH /v1/notes/{note_id}": "tenant",
    "DELETE /v1/notes/{note_id}": "tenant",
    "GET /v1/notes/{note_id}/evidence": "tenant",
    "POST /v1/lodging/parse-link": "user_scoped",
    "GET /v1/people": "user_scoped",
    "POST /v1/people": "user_scoped",
    "PUT /v1/people/{person_id}": "user_scoped",
    "DELETE /v1/people/{person_id}": "user_scoped",
    "PUT /v1/trips/{trip_id}/travelers": "tenant",
    "PUT /v1/trips/{trip_id}/members/me/traveler": "tenant",
    "DELETE /v1/trips/{trip_id}/members/me/traveler": "tenant",
    "GET /v1/trips/{trip_id}/activity": "tenant",
    "GET /v1/trips/{trip_id}/members": "tenant",
    "PATCH /v1/trips/{trip_id}/members/{user_id}": "tenant",
    "DELETE /v1/trips/{trip_id}/members/{user_id}": "tenant",
    "POST /v1/trips/{trip_id}/leave": "tenant",
    "POST /v1/trips/{trip_id}/transfer": "tenant",
    "GET /v1/trips/{trip_id}/invites": "tenant",
    "POST /v1/trips/{trip_id}/invites": "tenant",
    "DELETE /v1/trips/{trip_id}/invites/{invite_id}": "tenant",
    "GET /v1/trips/{trip_id}/share-links": "tenant",
    "POST /v1/trips/{trip_id}/share-links": "tenant",
    "PATCH /v1/trips/{trip_id}/share-links/{link_id}": "tenant",
    "DELETE /v1/trips/{trip_id}/share-links/{link_id}": "tenant",
    "GET /v1/shared/{token}": "public",
    "GET /v1/public/sample-trips": "public",
    "GET /v1/public/sample-trips/{slug}": "public",
    "POST /v1/public/sample-trips/{slug}/copy": "user_scoped",
    "GET /v1/invites/{token}": "public",
    "POST /v1/invites/{token}/accept": "user_scoped",
    "POST /v1/trips/{trip_id}/ai/explain": "tenant",
    "POST /v1/trips/{trip_id}/ai/packing-list": "tenant",
    "POST /v1/trips/{trip_id}/ai/draft-day": "tenant",
    "POST /v1/trips/{trip_id}/ai/draft-trip": "tenant",
    "GET /v1/trips/{trip_id}/agent-runs/preview": "tenant",
    "POST /v1/trips/{trip_id}/agent-runs": "tenant",
    "GET /v1/trips/{trip_id}/agent-runs": "tenant",
    "GET /v1/agent-runs/{run_id}": "tenant",
    "GET /v1/agent-runs/{run_id}/events": "tenant",
    "GET /v1/agent-runs/{run_id}/stream": "tenant",
    "POST /v1/agent-runs/{run_id}/cancel": "tenant",
    "GET /v1/me/agent-taster": "user_scoped",
    # Mounted only when AUTH_MODE=dev in local and ci (main.create_app).
    "GET /v1/dev/personas": "public",
    "POST /v1/dev/session": "public",
    # FastAPI's own documentation routes.
    "GET /openapi.json": "public",
    "GET /docs": "public",
    "GET /docs/oauth2-redirect": "public",
    "GET /redoc": "public",
}

# Tenant write routes a viewer may call (04 role table: a viewer can read and heart). "METHOD /path" keys.
VIEWER_WRITE_OK: set[str] = {"PUT /v1/lodging/{option_id}/votes/me", "POST /v1/trips/{trip_id}/leave", "PUT /v1/trips/{trip_id}/members/me/traveler", "DELETE /v1/trips/{trip_id}/members/me/traveler"}  # a viewer says which traveler they are
